name: Build iOS SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.14'
        check-latest: true
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@v0.0.0-20220112202225-6b2478e03d8d
        go install golang.org/x/mobile/cmd/gobind@v0.0.0-20220112202225-6b2478e03d8d
        export PATH=$PATH:$(go env GOPATH)/bin
        gomobile init
    
    - name: Build iOS Framework
      run: |
        cd go/hello
        export PATH=$PATH:$(go env GOPATH)/bin
        gomobile bind -target=ios -o ../../build/Hello.xcframework github.com/yourusername/gomobile_iosdemo/go/hello
    
    - name: Create Release Directory
      run: |
        mkdir -p release
    
    - name: Package Framework
      run: |
        cd build
        zip -r ../release/Hello.xcframework.zip Hello.xcframework
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hello.xcframework
        path: release/Hello.xcframework.zip 